# Generated by Django 4.2.30 on 2026-05-15 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to=settings.AUTH_USER_MODEL)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Head Officer'), (2, 'Regional Specialist')])),
                ('region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['region', 'user__username'],
            },
        ),
        migrations.AlterModelOptions(
            name='reportassignment',
            options={'ordering': ['due_date', '-updated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='reportassignment',
            name='unique_template_assignee',
        ),
        migrations.RemoveField(
            model_name='reportassignment',
            name='assignee',
        ),
        migrations.AddField(
            model_name='reportassignment',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportassignment',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reportassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportassignment',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reports.specialist'),
        ),
        migrations.RunSQL(
            sql='UPDATE reports_reportassignment SET assigned_by_id = NULL',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='reportassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='reports.specialist'),
        ),
        migrations.AddConstraint(
            model_name='reportassignment',
            constraint=models.UniqueConstraint(fields=('template', 'specialist'), name='unique_template_specialist'),
        ),
    ]
